name: Dispact remote workflow sync
description: Dispatch a workflow, wait it to run and output log.
author: Stephdotnet
branding:
  icon: refresh-cw
  color: green
outputs:
  run_id:
    description: The identified Run ID.
inputs:
  token:
    description: GitHub Personal Access Token for making API requests.
    required: true
  ref:
    description:
      The git reference for the workflow. The reference can be a branch or tag
      name.
    required: true
  repo:
    description: Repository of the action to dispatch.
    required: true
  owner:
    description: Owner of the given repository.
    required: true
  workflow:
    description:
      Workflow to return an ID for. Can be the ID or the workflow filename.
    required: true
  workflow_inputs:
    description:
      A flat JSON object, only supports strings, numbers, and booleans (as per
      workflow inputs API).
  workflow_timeout_seconds:
    description: Time until giving up waiting for the start of the workflow run.
    default: 300
  poll_interval_ms:
    description: Frequency to poll the run for a status.
    default: 5000
runs:
  using: node20
  main: dist/index.js
